// Autogenerated code. Do not edit.
package amqp

const FrameMethod = 1

const FrameHeader = 2

const FrameBody = 3

const FrameHeartbeat = 8

const FrameMinSize = 4096

const FrameEnd = 206

const ReplySuccess = 200

const ContentTooLarge = 311

const NoConsumers = 313

const ConnectionForced = 320

const InvalidPath = 402

const AccessRefused = 403

const NotFound = 404

const ResourceLocked = 405

const PreconditionFailed = 406

const FrameError = 501

const SyntaxError = 502

const CommandInvalid = 503

const ChannelError = 504

const UnexpectedFrame = 505

const ResourceError = 506

const NotAllowed = 530

const NotImplemented = 540

const InternalError = 541

const ClassConnection = 10

const MethodConnectionStart = 10

const MethodConnectionStartOk = 11

const MethodConnectionSecure = 20

const MethodConnectionSecureOk = 21

const MethodConnectionTune = 30

const MethodConnectionTuneOk = 31

const MethodConnectionOpen = 40

const MethodConnectionOpenOk = 41

const MethodConnectionClose = 50

const MethodConnectionCloseOk = 51

const MethodConnectionBlocked = 60

const MethodConnectionUnblocked = 61

const ClassChannel = 20

const MethodChannelOpen = 10

const MethodChannelOpenOk = 11

const MethodChannelFlow = 20

const MethodChannelFlowOk = 21

const MethodChannelClose = 40

const MethodChannelCloseOk = 41

const ClassExchange = 40

const MethodExchangeDeclare = 10

const MethodExchangeDeclareOk = 11

const MethodExchangeDelete = 20

const MethodExchangeDeleteOk = 21

const MethodExchangeBind = 30

const MethodExchangeBindOk = 31

const MethodExchangeUnbind = 40

const MethodExchangeUnbindOk = 51

const ClassQueue = 50

const MethodQueueDeclare = 10

const MethodQueueDeclareOk = 11

const MethodQueueBind = 20

const MethodQueueBindOk = 21

const MethodQueueUnbind = 50

const MethodQueueUnbindOk = 51

const MethodQueuePurge = 30

const MethodQueuePurgeOk = 31

const MethodQueueDelete = 40

const MethodQueueDeleteOk = 41

const ClassBasic = 60

const MethodBasicQos = 10

const MethodBasicQosOk = 11

const MethodBasicConsume = 20

const MethodBasicConsumeOk = 21

const MethodBasicCancel = 30

const MethodBasicCancelOk = 31

const MethodBasicPublish = 40

const MethodBasicReturn = 50

const MethodBasicDeliver = 60

const MethodBasicGet = 70

const MethodBasicGetOk = 71

const MethodBasicGetEmpty = 72

const MethodBasicAck = 80

const MethodBasicReject = 90

const MethodBasicRecoverAsync = 100

const MethodBasicRecover = 110

const MethodBasicRecoverOk = 111

const MethodBasicNack = 120

const ClassTx = 90

const MethodTxSelect = 10

const MethodTxSelectOk = 11

const MethodTxCommit = 20

const MethodTxCommitOk = 21

const MethodTxRollback = 30

const MethodTxRollbackOk = 31

const ClassConfirm = 85

const MethodConfirmSelect = 10

const MethodConfirmSelectOk = 11

var ConstantsNameMap = map[uint16]string{

	1: "FRAME_METHOD",

	2: "FRAME_HEADER",

	3: "FRAME_BODY",

	8: "FRAME_HEARTBEAT",

	4096: "FRAME_MIN_SIZE",

	206: "FRAME_END",

	200: "REPLY_SUCCESS",

	311: "CONTENT_TOO_LARGE",

	313: "NO_CONSUMERS",

	320: "CONNECTION_FORCED",

	402: "INVALID_PATH",

	403: "ACCESS_REFUSED",

	404: "NOT_FOUND",

	405: "RESOURCE_LOCKED",

	406: "PRECONDITION_FAILED",

	501: "FRAME_ERROR",

	502: "SYNTAX_ERROR",

	503: "COMMAND_INVALID",

	504: "CHANNEL_ERROR",

	505: "UNEXPECTED_FRAME",

	506: "RESOURCE_ERROR",

	530: "NOT_ALLOWED",

	540: "NOT_IMPLEMENTED",

	541: "INTERNAL_ERROR",
}
